### ISSUE TITLE
Would it be possible to add a NeuroML validator to neuroml-db.org

### ISSUE THREAD

**Issue by sanjayankur31** [scrook/neuroml-db#123]
Since we've moved our docs to a static GitHub pages website at docs.neuroml.org, we can't do a lot of advanced tasks with it, like add a web-based validator where people can quickly upload their model file and see if it's valid.

Is this perhaps possible to add to neuroml-db?

**Comment by JustasB** [comment]
I remember a while back there was a NeuroML validator link in the top menu of neuroml.org (https://neuroml.org/validate). 

It says now that the validator is under construction. 

Could the validator be updated on neuroml.org and a link to it be placed in the new NeuroML docs?

I'm concerned that validating NeuroML is not a functionality of the NeuroML-DB _per se_ and that the neuroml.org website is a more appropriate place for it.

@scrook @pgleeson

**Comment by pgleeson** [comment]
@JustasB Yes, there was a NML v1 validator there, but that broke some time ago following some updates to the NML website (the move to Ruby on Rails). It wasn't a priority to fix as v1 was deprecated.

The issue now is that it would be nice to have a validator for v2 (using jNeuroML/pyNeuroML in the background), but since the docs.neuroml.org are hosted on a static site on GH pages, and the existing neuroml.org will become a slimmed down version pointing to the new docs, there's nowhere to host something running jnml for the validator. The enquiry was really whether the neuroml-db.org infrastructure could be updated to host this, but indeed as you say, it makes more sense to have the validator at the main nml site.
